# Generated by Django 3.2.8 on 2021-10-21 08:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=200, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('item_image', models.ImageField(upload_to='')),
                ('item_price', models.CharField(max_length=200)),
                ('item_status', models.CharField(choices=[('USED', 'USED'), ('NEW', 'NEW')], max_length=100)),
                ('item_special_deal', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200)),
                ('item_special_offer', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200)),
                ('item_sub_image1', models.ImageField(upload_to='')),
                ('item_sub_image2', models.ImageField(upload_to='')),
                ('item_sub_image3', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Men_wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=200, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('item_image', models.ImageField(upload_to='')),
                ('item_price', models.CharField(max_length=200)),
                ('item_status', models.CharField(choices=[('USED', 'USED'), ('NEW', 'NEW')], max_length=100)),
                ('item_special_deal', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200)),
                ('item_special_offer', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200)),
                ('item_sub_image1', models.ImageField(upload_to='')),
                ('item_sub_image2', models.ImageField(upload_to='')),
                ('item_sub_image3', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Scarves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=200, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('item_image', models.ImageField(upload_to='')),
                ('item_price', models.CharField(max_length=200)),
                ('item_status', models.CharField(choices=[('USED', 'USED'), ('NEW', 'NEW')], max_length=100)),
                ('item_special_deal', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200)),
                ('item_special_offer', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Women_wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=200, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('item_image', models.ImageField(upload_to='')),
                ('item_price', models.CharField(max_length=200)),
                ('item_status', models.CharField(choices=[('USED', 'USED'), ('NEW', 'NEW')], max_length=100)),
                ('item_special_deal', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200)),
                ('item_special_offer', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200)),
                ('item_sub_image1', models.ImageField(upload_to='')),
                ('item_sub_image2', models.ImageField(upload_to='')),
                ('item_sub_image3', models.ImageField(upload_to='')),
            ],
        ),
    ]
