# Generated by Django 3.2.8 on 2021-10-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women_wear',
            name='item_sub_image3',
        ),
        migrations.AlterField(
            model_name='bags',
            name='item_image',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='bags',
            name='item_sub_image1',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='bags',
            name='item_sub_image2',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='bags',
            name='item_sub_image3',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='men_wear',
            name='item_image',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='men_wear',
            name='item_sub_image1',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='men_wear',
            name='item_sub_image2',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='men_wear',
            name='item_sub_image3',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='scarves',
            name='item_image',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='women_wear',
            name='item_image',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='women_wear',
            name='item_sub_image1',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='women_wear',
            name='item_sub_image2',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
