# Generated by Django 4.0.2 on 2022-02-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_special_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_offer',
            name='item_number',
            field=models.CharField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
