# Generated by Django 4.0.2 on 2022-02-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_special_offer_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_offer',
            name='item_number',
            field=models.CharField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
