# Generated by Django 4.0.3 on 2022-03-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_special'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Special_offer',
        ),
    ]
