# Generated by Django 4.0.3 on 2022-04-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_special_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_number', models.CharField(max_length=150, unique=True)),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_position', models.CharField(max_length=200)),
                ('agent_contact', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
