# Generated by Django 4.0.4 on 2022-07-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_contact_us_agent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='women_wear',
            name='men_wear',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.men_wear'),
            preserve_default=False,
        ),
    ]
