# Generated by Django 4.0.4 on 2022-07-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_women_wear_men_wear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women_wear',
            name='men_wear',
        ),
    ]
