# Generated by Django 4.0.4 on 2022-07-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_women_wear_men_wear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women_wear',
            name='men_wear',
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('men_wear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.men_wear')),
            ],
        ),
    ]
